.PHONY: help clean test train serve
help:  ## Show help
    @awk 'BEGIN {FS = ":."##"; printf "\nUSAGE:\n make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2} /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0,5) } ' $(MAKEFILE_LIST)
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

del-model:
	rm -rf ./models/*
clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo|.ruff_cache|.venv|\.egg-info|.pytest_cache|.ipynb_checkpoints|.ruff_cache|.gradio|cdk.out)" | xargs rm -rf
	rm -f .coverage
	find . -type f -name "uv.lock" -ls -delete

requires:
	uv export --format requirements.txt --output-file requirements.txt --no-editable  --no-hashes --no-annotate 


download-data:
	python data/download_html.py
get-corpous:
	python data/corpus_create.py

train-tokenizer:
	python train.py

build-image:
	docker build -t tamil-tiktok:latest .

serve:
	python -m serve 
gradio:
	python app.py
	